services:
  backend:
    build:
      context: ./flask_backend  
      dockerfile: Dockerfile      
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - JAWSDB_URL=${JAWSDB_URL}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - FRED_KEY=${FRED_KEY}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
      - REACT_APP_BACKEND_URL=http://backend:5000

  frontend:
    build:
      context: .                
      dockerfile: ./src/Dockerfile 
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    volumes:
      - ./src:/app                
    depends_on:
      - backend
