apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: expense-tracker
    tier: backend
spec:
  selector:
    app: expense-tracker
    tier: backend
  ports:
    - protocol: TCP
      port: 5000      
      nodePort: 31080
  type: NodePort
